# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DesktopProgram\sample\sample_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from DesktopProgram.utils import get_items_response, get_response_server
import DesktopProgram.img.menu_images_rc


class Ui_WhatsEat(object):
    def __init__(self, session, ADDRESS_SERVER):
        self.session = session
        self.ADDRESS_SERVER = ADDRESS_SERVER
        self.list_answer_recipes = dict()

    def setupUi(self, WhatsEat):
        WhatsEat.setObjectName("WhatsEat")
        WhatsEat.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WhatsEat.sizePolicy().hasHeightForWidth())
        WhatsEat.setSizePolicy(sizePolicy)
        WhatsEat.setMinimumSize(QtCore.QSize(1024, 768))
        WhatsEat.setMaximumSize(QtCore.QSize(1024, 768))
        WhatsEat.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.centralwidget = QtWidgets.QWidget(WhatsEat)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setObjectName("centralwidget")
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 60, 200))
        self.menu_bar.setStyleSheet("background-color: rgb(56, 56, 56);\n"
                                    "border-bottom-right-radius: 10px;")
        self.menu_bar.setObjectName("menu_bar")
        self.menu_search = QtWidgets.QPushButton(self.menu_bar)
        self.menu_search.setGeometry(QtCore.QRect(5, 11, 50, 50))
        self.menu_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/menu_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_search.setIcon(icon)
        self.menu_search.setIconSize(QtCore.QSize(50, 50))
        self.menu_search.setCheckable(False)
        self.menu_search.setObjectName("menu_search")
        self.menu_search.clicked.connect(self._get_search_window)
        self.menu_login = QtWidgets.QPushButton(self.menu_bar)
        self.menu_login.setGeometry(QtCore.QRect(5, 76, 50, 50))
        self.menu_login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu/menu_profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_login.setIcon(icon1)
        self.menu_login.setIconSize(QtCore.QSize(50, 50))
        self.menu_login.setObjectName("menu_login")
        self.menu_login.clicked.connect(self._get_login_window)
        self.menu_help = QtWidgets.QPushButton(self.menu_bar)
        self.menu_help.setGeometry(QtCore.QRect(5, 141, 50, 50))
        self.menu_help.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu/menu_help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_help.setIcon(icon2)
        self.menu_help.setIconSize(QtCore.QSize(50, 50))
        self.menu_help.setObjectName("menu_help")
        self.menu_help.clicked.connect(self._get_help_window)
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(94, 36, 868, 89))
        self.header.setObjectName("header")
        self.header_name = QtWidgets.QLabel(self.header)
        self.header_name.setGeometry(QtCore.QRect(10, 0, 811, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.header_name.setFont(font)
        self.header_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.header_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.header_name.setObjectName("header_name")
        self.header_name.setText("Подобрать блюдо на ужин")
        self.line = QtWidgets.QLabel(self.header)
        self.line.setGeometry(QtCore.QRect(8, 44, 858, 10))
        self.line.setStyleSheet("background-color: rgb(231, 180, 0);")
        self.line.setText("")
        self.line.setObjectName("line")
        self.catalog = QtWidgets.QLabel(self.header)
        self.catalog.setGeometry(QtCore.QRect(10, 62, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.catalog.setFont(font)
        self.catalog.setStyleSheet("color: rgb(255, 255, 255);")
        self.catalog.setObjectName("catalog")
        self.catalog.setText("Книга рецептов")
        self.content_area = QtWidgets.QWidget(self.centralwidget)
        self.content_area.setGeometry(QtCore.QRect(99, 141, 868, 583))
        self.content_area.setStyleSheet("")
        self.content_area.setObjectName("content_area")
        self.search_panel = QtWidgets.QWidget(self.content_area)
        self.search_panel.setGeometry(QtCore.QRect(5, 5, 858, 99))
        self.search_panel.setMinimumSize(QtCore.QSize(858, 99))
        self.search_panel.setMaximumSize(QtCore.QSize(858, 99))
        self.search_panel.setStyleSheet("border-radius: 10px;\n"
                                        "background-color: rgb(56, 56, 56);")
        self.search_panel.setObjectName("search_panel")
        self.search_label = QtWidgets.QLabel(self.search_panel)
        self.search_label.setGeometry(QtCore.QRect(20, 22, 100, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_label.setFont(font)
        self.search_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "font: 18pt \"Times New Roman\";")
        self.search_label.setObjectName("label")
        self.search_label.setText("Поиск:")
        self.input_product = QtWidgets.QLineEdit(self.search_panel)
        self.input_product.setGeometry(QtCore.QRect(10, 52, 667, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.input_product.setFont(font)
        self.input_product.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-top-left-radius: 5px;\n"
                                    "border-bottom-left-radius: 5px;\n"
                                    "border-top-right-radius: 0;\n"
                                    "border-bottom-right-radius: 0;")
        self.input_product.setObjectName("lineEdit")
        self.search_recipes = QtWidgets.QPushButton(self.search_panel)
        self.search_recipes.setGeometry(QtCore.QRect(676, 52, 170, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.search_recipes.setFont(font)
        self.search_recipes.setStyleSheet("background-color: rgb(231, 180, 0);\n"
                                          "border-radius:5px;\n"
                                          "border-top-left-radius: 0;\n"
                                          "border-bottom-left-radius: 0;")
        self.search_recipes.setObjectName("search_recipes")
        self.search_recipes.setText("Подобрать рецепт")
        self.search_recipes.clicked.connect(self._send_request)
        self.list_recipes = QtWidgets.QWidget(self.content_area)
        self.list_recipes.setGeometry(QtCore.QRect(5, 136, 858, 447))
        self.list_recipes.setObjectName("list_recipes")
        self.load_more = QtWidgets.QPushButton(self.list_recipes)
        self.load_more.setGeometry(QtCore.QRect(360, 410, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.load_more.setFont(font)
        self.load_more.setStyleSheet("background-color: rgb(231, 180, 0);\n"
                                     "border-radius: 5px;")
        self.load_more.setObjectName("load_more")
        self.load_more.clicked.connect(self._get_next_recipes)
        WhatsEat.setCentralWidget(self.centralwidget)

        self.retranslateUi(WhatsEat)
        QtCore.QMetaObject.connectSlotsByName(WhatsEat)

    def retranslateUi(self, WhatsEat):
        _translate = QtCore.QCoreApplication.translate
        WhatsEat.setWindowTitle(_translate("WhatsEat", "WhatsEat"))

        self.load_more.setText(_translate("WhatsEat", "Загрузить еще"))

    def _get_search_window(self):
        print("Search load")

    def _get_login_window(self):
        print("Login load")

    def _get_help_window(self):
        print("Help load")

    def _get_next_recipes(self):
        print("Next recipes load")

    def _preparation_form(self, recipe: dict, target, geometry: dict):
        recipe_form = QtWidgets.QWidget(target)
        recipe_form.setGeometry(QtCore.QRect(geometry['x'], geometry['y'], 268, 384))
        recipe_form.setStyleSheet("background-color: rgb(56, 56, 56);\n"
                                  "border-radius: 10px;")
        recipe_form.setObjectName("recipe")
        recipe_image = QtWidgets.QLabel(recipe_form)
        recipe_image.setGeometry(QtCore.QRect(10, 11, 248, 170))
        recipe_image.setText("")
        try:
            recipe_image.setPixmap(QtGui.QPixmap(recipe['img']))
        except Exception:
            recipe_image.setPixmap(QtGui.QPixmap(":/preview_image/image-recipe.png"))

            print('load image')
        recipe_image.setScaledContents(True)
        recipe_image.setObjectName("recipe_image")
        recipe_name = QtWidgets.QLabel(recipe_form)
        recipe_name.setGeometry(QtCore.QRect(10, 197, 248, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        recipe_name.setFont(font)
        recipe_name.setStyleSheet("color: rgb(255, 255, 255);")
        recipe_name.setObjectName("recipe_name")
        recipe_name.setText(recipe['title'])
        recipe_description = QtWidgets.QLabel(recipe_form)
        recipe_description.setGeometry(QtCore.QRect(10, 238, 248, 140))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        recipe_description.setFont(font)
        recipe_description.setStyleSheet("color: rgb(255, 255, 255);")
        recipe_description.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        recipe_description.setObjectName("recipe_des")
        recipe_description.setText(recipe['description'])
        recipe_form.show()

    def _getting_recipes(self, answer_server):
        for widget in self.list_recipes.children():
            widget.deleteLater()
        column = 0
        row = 0
        for recipe in answer_server:
            if column > 2:
                row += 1
                column = 0
            x = self._get_geometry_x(column)
            self._preparation_form(recipe, self.list_recipes, {'x': x, 'y': 0})
            column += 1

    @staticmethod
    def _get_geometry_x(column):
        margin = 27
        width_card = 268
        return (column * width_card + column * margin)

    def _send_request(self):
        text_input = self.input_product.text()
        item_response = get_items_response()
        answer_server = self.session.get(get_response_server(self.ADDRESS_SERVER, item_response, text_input))
        answer_server = answer_server.json()
        i = 0
        list_recipes = 1
        temp = []
        for recipe in answer_server:
            if i < 2:
                temp.append(recipe)
                i += 1
            else:
                temp.append(recipe)
                self.list_answer_recipes[f'{list_recipes}'] = temp
                list_recipes += 1
                temp = []
                i = 0
        self.list_answer_recipes[f'{list_recipes}'] = temp
        self._getting_recipes(self.list_answer_recipes['1'])
