# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from DesktopProgram.utils import get_items_response, get_response_server


class Ui_MainWindow(object):
    def __init__(self, session, ADDRESS_SERVER):
        self.session = session
        self.ADDRESS_SERVER = ADDRESS_SERVER

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 920)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 920))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 920))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setWhatsThis("")
        MainWindow.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1220, 920))
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1220, 920))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.list_recipes = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.list_recipes.setGeometry(QtCore.QRect(24, 170, 1172, 9000))
        self.list_recipes.setObjectName("list_recipes")
        self.preview = QtWidgets.QLabel(self.list_recipes)
        self.preview.setGeometry(QtCore.QRect(360, 0, 501, 750))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.preview.setFont(font)
        self.preview.setStyleSheet("color: rgb(255, 255, 255);")
        self.preview.setObjectName("preview")
        self.search_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.search_panel.setGeometry(QtCore.QRect(24, 32, 1172, 106))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_panel.sizePolicy().hasHeightForWidth())
        self.search_panel.setSizePolicy(sizePolicy)
        self.search_panel.setMinimumSize(QtCore.QSize(1172, 106))
        self.search_panel.setMaximumSize(QtCore.QSize(1172, 106))
        self.search_panel.setStyleSheet("border-radius:10px;background-color: rgb(56, 56, 56);")
        self.search_panel.setObjectName("search_panel")
        self.input_product = QtWidgets.QLineEdit(self.search_panel)
        self.input_product.setGeometry(QtCore.QRect(12, 55, 909, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.input_product.setFont(font)
        self.input_product.setStyleSheet(
            "color: rgb(0, 0, 0);background-color: rgb(255, 255, 255);border-top-left-radius: 10px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 10px;border-top-color: rgb(44, 44, 44);border-top-style: solid;border-top-width: 1px;border-right-color: rgb(44, 44, 44);border-right-style: solid;border-right-width: 1px;border-bottom-color: rgb(44, 44, 44);border-bottom-style: solid;border-bottom-width: 1px;border-left-color: rgb(44, 44, 44);border-left-style: solid;border-left-width: 1px;border-image-source: initial;border-image-slice: initial;    border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;")
        self.input_product.setText("")
        self.input_product.setObjectName("input_product")
        self.search_recipe = QtWidgets.QPushButton(self.search_panel)
        self.search_recipe.setGeometry(QtCore.QRect(921, 55, 230, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.search_recipe.setFont(font)
        self.search_recipe.setStyleSheet(
            "background-color: rgb(231, 180, 0);border-color: rgb(44, 44, 44);border-top-left-radius: 0px;border-top-right-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 0px;")
        self.search_recipe.setObjectName("search_recipe")
        self.search_recipe.clicked.connect(self._send_request)
        self.search_label = QtWidgets.QLabel(self.search_panel)
        self.search_label.setGeometry(QtCore.QRect(16, 16, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.search_label.setFont(font)
        self.search_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.search_label.setObjectName("search_label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhatsEat"))
        self.preview.setText(_translate("MainWindow", "Здесь будут подходящие рецепты"))
        self.search_recipe.setText(_translate("MainWindow", "Подобрать рецепт"))
        self.search_label.setText(_translate("MainWindow", "Введите ингредиенты:"))

    def _preparation_form(self, recipe: dict, target, geometry: dict):
        recipe_form = QtWidgets.QWidget(target)
        recipe_form.setGeometry(QtCore.QRect(geometry['x'], geometry['y'], 380, 537))
        recipe_form.setMinimumSize(QtCore.QSize(380, 537))
        recipe_form.setStyleSheet('background-color: rgb(56, 56, 56);border-radius: 10px;')
        recipe_form.setMaximumSize(QtCore.QSize(380, 537))
        image = QtWidgets.QLabel(recipe_form)
        image.setGeometry(QtCore.QRect(10, 10, 360, 225))
        image.setStyleSheet('border-radius: 10px')
        temp_image = QtGui.QPixmap(360, 225)
        temp_image.load('image-recipe.png')
        image.setPixmap(temp_image)
        label = QtWidgets.QLabel(recipe_form)
        label.setText(recipe['title'])
        label.setGeometry(QtCore.QRect(10, 235, 360, 33))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        label.setFont(font)
        label.setStyleSheet("color: rgb(255, 255, 255);")
        description = QtWidgets.QLabel(recipe_form)
        description.setGeometry(QtCore.QRect(10, 268, 360, 259))
        description.setText(recipe['description'])
        description.setStyleSheet("color: rgb(255, 255, 255);")
        description.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        description.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        description.setFont(font)
        recipe_form.show()

    def _getting_recipes(self, answer_server):
        for widget in self.list_recipes.children():
            widget.deleteLater()
        column = 0
        row = 0
        for recipe in answer_server:
            if column > 2:
                row += 1
                column = 0
            x = self._get_geometry_x(column)
            y = self._get_geometry_y(row)
            self._preparation_form(recipe, self.list_recipes, {'x': x, 'y': y})
            column += 1
            # self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1172, self._get_geometry_y(row + 1)))

    @staticmethod
    def _get_geometry_x(column):
        margin = 16
        width_card = 380
        return (column * width_card + column * margin)

    @staticmethod
    def _get_geometry_y(row):
        margin = 16
        height_card = 537
        return (row * height_card + row * margin)

    def _send_request(self):
        text_input = self.input_product.text()
        item_response = get_items_response()
        answer_server = self.session.get(get_response_server(self.ADDRESS_SERVER, item_response, text_input))
        answer_server = answer_server.json()
        self._getting_recipes(answer_server)
